#!/bin/bash

# IBM(c) 2007 EPL license http://www.eclipse.org/legal/epl-v10.html

# Common script to make any one the xcat rpms.  To build locally, run in the top dir of local svn repository, for example:
#   ./makepythonrpm xcat-inventory

function makepythoncli {
    RPMNAME="$1"
    SPEC_FILE="xcat-inventory.spec"
    sed -i s/%%REPLACE_CURRENT_VERSION%%/${VER}/g $RPMNAME/${SPEC_FILE}
    tar --exclude .svn -czvf $RPMROOT/SOURCES/$RPMNAME-${VER}.tar.gz $RPMNAME
    rm -f $RPMROOT/SRPMS/$RPMNAME-$VER*rpm $RPMROOT/RPMS/noarch/$RPMNAME-$VER*rpm
    echo "Building $RPMROOT/RPMS/noarch/$RPMNAME-$VER-snap*.noarch.rpm $EMBEDTXT..."
    rpmbuild --quiet -ta $RPMROOT/SOURCES/$RPMNAME-${VER}.tar.gz --define "version $VER" $REL "$EASE"
    if [ $? -eq 0 ]; then
        ls $RPMROOT/RPMS/noarch/$RPMNAME-$VER-snap*.noarch.rpm
        exit 0
    else  
        exit 1
    fi
}	
	
# Main code....

if [ -z "$1" ]; then
    echo 'Usage: makepythonrpm xcat-inventory'
    exit 1
fi

OSNAME=$(uname)
VER=`cat Version`
REL="--define"
EASE='usedate 1'
RPMROOT=/root/rpmbuild

rpmbuild --version > /dev/null
if [ $? -gt 0 ]; then
   echo "Error: rpmbuild does not appear to be installed or working."
   exit 2
fi

if [ "$1" = "xcat-inventory" ]; then
        makepythoncli $1
fi

