#!/usr/bin/env python

from __future__ import print_function
import sys
from inventorydiff import InventoryDiff

if __name__=="__main__":
    if(len(sys.argv) != 4):
        print("invdiff <file1> <file2> <sourcetype>",file=sys.stderr)
        exit(1)

    fn1=sys.argv.pop(1)
    fn2=sys.argv.pop(1)
    srctype = sys.argv.pop(1)

    InventoryDiff(fn1, fn2, srctype).ShowDiff()
